# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a983ba4d0ca886867bdc01ba6b3b8ec8ce103a166a821c68ef3c9d832c29afcebe625fa8f881e7f003021bddeab858a9b8cb7fb2c7986cb313debbf626cd5d4

test:
  secret_key_base: 778df565076640a04143d7d0eb8aadf99d71e28bba65d3bf1b0123f5d53c81f5362b9a6e986fd2c227f836e1fac6fd0d77d8d42463ad17e0b1add8f898fe0dd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
